require 'custom.options.netrw'
require 'custom.options.which-key'
require 'custom.options.conform'
require 'custom.options.markdown'
require 'custom.options.spell'
require 'custom.options.lspconfig'
require 'custom.options.undo'
